In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path
import sys

# Project root
PROJECT_ROOT = Path.cwd().parents[1]
sys.path.append(str(PROJECT_ROOT))

from modules import metrics
from modules import read_timeseries as read

In [3]:
# reading files
base_dir = Path(r'C:\Users\karoa\MOHID_internship\MOHID_single_domain\res')

folders = ['Run1', 'Run2', 'Run3']
name = '36_17' 

all_results = {folder: read.read_files(folder, name, base_dir) for folder in folders}

# calculate sensitivity index
sis = metrics.compare_all_runs(all_results, metrics.sensitivity_index,reference_key='Run1')
RMSE = metrics.compare_all_runs(all_results, metrics.rmse,reference_key='Run1')

# convert to dataframes per layer instead of per run
sis_by_layer = metrics.by_layer(sis)

In [7]:
rmse = metrics.compare_vs_reference(all_results['Run1'], all_results['Run1'], metrics.rmse, columns=None)
rmse

,velocity_U,velocity_V,velocity_W,velocity_modulus,velocity_direction,water_level,OpenPoint,salinity,temperature
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
sis_by_layer[13]

,velocity_U,velocity_V,velocity_W,velocity_modulus,velocity_direction,water_level,OpenPoint,salinity,temperature
run,,,,,,,,,
Run2,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
Run3,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0